import './bootstrap';
import { gsap } from "gsap";
import Swiper from 'swiper/bundle';
// import { Autoplay } from 'swiper';
// import { Navigation, Pagination } from 'swiper/modules';
import 'swiper/css/bundle';
import { ScrollTrigger } from "gsap/ScrollTrigger";
window.gsap = gsap;
window.Swiper=Swiper;
window.ScrollTrigger = ScrollTrigger;
